// sonar properties updates

sonar.projectKey=job-portal-application_user_service
sonar.organization=job-portal-application
sonar.sources=src
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts
sonar.exclusions=node_modules/**, coverage/**, dist/**
sonar.javascript.lcov.reportPaths=coverage/lcov.info
sonar.sourceEncoding=UTF-8